version: '3.4'

services:
  ticketburst-services-search:
    image: ticketburst-services-search:v0
    build:
      context: ../../backend
      dockerfile: TicketBurst.SearchService/Dockerfile
  ticketburst-services-reservation:
    image: ticketburst-services-reservation:v0
    build:
      context: ../../backend
      dockerfile: TicketBurst.ReservationService/Dockerfile
