---
apiVersion: v1
kind: Service
metadata:
  name: ticketburst-reservation-service
  labels:
    app: ticketburst
    appsvc: ticketburst-reservation
spec:
  type: LoadBalancer
  selector:
    appsvc: ticketburst-reservation
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ticketburst-reservation-statefulset
spec:
  serviceName: ticketburst-reservation-service
  selector:
    matchLabels:
      appsvc: ticketburst-reservation
  replicas: 2
  template:
    metadata:
      labels:
        app: ticketburst
        appsvc: ticketburst-reservation
    spec:
      serviceAccountName: default
      nodeSelector:
        appsvc: ticketburst-reservation
      containers:
      - name: ticketburst-services-reservation
        image: 381777116710.dkr.ecr.eu-south-1.amazonaws.com/ticketburst-reservation:93894ef
        ports:
        - containerPort: 80
        command: ["/app/reservationd"]
        args: ["--aws"]
        env:
        - name: TICKETBURST_SERVICEMAP_SEARCH
          value: ticketburst-search-service.default
        - name: TICKETBURST_SERVICEMAP_RESERVATION
          value: ticketburst-reservation-service.default
        - name: TICKETBURST_SERVICEMAP_CHECKOUT
          value: ticketburst-checkout-service.default
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName          
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: reservation-cluster
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - statefulsets
      - statefulsets/scale
      - statefulsets/status
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: reservation-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: reservation-cluster
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: reservation-statefulsets-cluster
rules:
  - apiGroups:
      - "apps"
    resources:
      - pods
      - statefulsets
      - statefulsets/scale
      - statefulsets/status
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: reservation-statefulsets-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reservation-statefulsets-cluster
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
