---
apiVersion: v1
kind: Service
metadata:
  name: ticketburst-reservation-service
  labels:
    app: ticketburst
    appsvc: ticketburst-reservation
spec:
  type: LoadBalancer
  selector:
    appsvc: ticketburst-reservation
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketburst-reservation-deployment
spec:
  selector:
    matchLabels:
      appsvc: ticketburst-reservation
  replicas: 1
  template:
    metadata:
      labels:
        app: ticketburst
        appsvc: ticketburst-reservation
    spec:
      nodeSelector:
        appsvc: ticketburst-reservation
      containers:
      - name: ticketburst-services-reservation
        image: 381777116710.dkr.ecr.eu-south-1.amazonaws.com/ticketburst-reservation:46f0610
        ports:
        - containerPort: 80
        env:
        - name: TICKETBURST_SERVICEMAP_SEARCH
          value: ticketburst-search-service.default
        - name: TICKETBURST_SERVICEMAP_RESERVATION
          value: ticketburst-reservation-service.default
        - name: TICKETBURST_SERVICEMAP_CHECKOUT
          value: ticketburst-checkout-service.default
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName          
---
